
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './foundrysync'

      - id: foundrysync
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: sei-mmcdonough
          repo: moodle-mod_foundrysync
          excludes: prerelease, draft
     
      - name: package
        run: |
          OLDVERSION=${{ steps.foundrysync.outputs.release }}
          OLDDATE=`echo $OLDVERSION | cut -b 1-8`
          NEWDATE=`date +%Y%m%d`
          if [ $OLDDATE -ne $NEWDATE ]; then
              NEWVERSION=$NEWDATE\01
          else
              OLDVERS=`echo $OLDVERSION | cut -b 9-10`
              OLDVERS=${OLDVERS#0}
              let NEWVERS=(OLDVERS + 1)
              NEWVERSION=$OLDDATE`printf %02d $NEWVERS`
          fi
          PREVIOUSVERSION=$(grep "plugin->version" foundrysync/version.php | sed -e "s/.*= \(.*\);.*/\1/")
          sed -i "s#$PREVIOUSVERSION#$NEWVERSION#" foundrysync/version.php
          zip -r tool_foundrysync_$NEWVERSION.zip foundrysync/ -x  "foundrysync/*.git*"
          echo ::set-env name=artifact_version::$NEWVERSION
          echo ::set-env name=artifact_name::mod_groupquiz_$NEWVERSION      

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 2020101401 #${{ env.artifact_version }}
          release_name: tool_foundrysync_2020101401 #${{ env.artifact_name }}
          draft: false
          prerelease: false
