
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './foundrysync'

      - id: foundrysync
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          owner: sei-mmcdonough
          repo: moodle-mod_foundrysync
          excludes: prerelease, draft

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 2020101401 #${{ env.artifact_version }}
          release_name: tool_foundrysync_2020101401 #${{ env.artifact_name }}
          draft: false
          prerelease: false
